# Generated by Django 5.1.1 on 2024-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
